eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9195
spring:
  application:
    name: association
  datasource:
    url: jdbc:postgresql://localhost:5433/association
    username: sofia
    password: sofia
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    donations-url: http://localhost:8222/api/v1/donations
    users-url: http://localhost:8222/api/v1/users